<?php

namespace App\Console\Commands;

use App\Models\Subscription;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class StorePeriodicData extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:store-periodic-data';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'save the periodic data to disk';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        // get all subscriptions that are periodic
        $subs = Subscription::query()
            ->join("subscription_type", 'subscription.subscription_type', '=', 'subscription_type.id')
            ->where("subscription_type.type", 'like', '%periodic%')
            ->get(["subscription.*"]);


        // get the data for each subscription and svae to disk
        foreach ($subs as $sub) {
            // seconds*minutes*hours*days
            $lookBackSeconds = 60*60*12;

            $currentDate = date('Y-m-d', time());
            $lastWeekDate = date('Y-m-d', time() - $lookBackSeconds);

            // select the data we want for the subscription
            // we use raw sql because the query builder returned strange and incorrect results.
            // we also dont need to use prepared queries because all data we use is 
            // generated by the application and not the user
            $measurements = DB::select("
select m.* from subscription_station ss
    inner join measurement m on ss.station = m.stn
where
    ss.subscription = ". $sub["id"]." and
    timestamp(m.date, m.time) between DATE_ADD(now(), interval -24 hour) and now();
");

            // filter out null valls
            $a = json_decode(json_encode($measurements), true);
            for($i = 0; $i < count($a); $i++) {
                foreach ($a[$i] as $k => $v) {
                    if ($v == null) {
                        unset($a[$i][$k]);
                    }
                }
            }

            // insert data into array
            $diskData = [
                "measurements" => $a
            ];

            // save the data on the disk
            Storage::disk('weatherData')->put($sub["apikey"] . ".json", json_encode($diskData));
        }

    }
}
